name: pol_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.2 # اضافه شد جهت ذخیره توکن و ورود خودکار

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Untitled design.png
    - assets/Untitled_design-removebg-preview.png

  fonts:
    - family: Ravi
      fonts:
        - asset: assets/fonts/Ravi-Black.ttf
        - asset: assets/fonts/Ravi-Bold.ttf
        - asset: assets/fonts/Ravi-ExtraBold.ttf
        - asset: assets/fonts/Ravi-Light.ttf
        - asset: assets/fonts/Ravi-Medium.ttf
        - asset: assets/fonts/Ravi-Regular.ttf
        - asset: assets/fonts/Ravi-SemiBold.ttf
        - asset: assets/fonts/Ravi-Thin.ttf